library_management_system/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("lms.urls")),
]

lms/urls.py
from django.urls import path

from . import views

app_name = "lms"
urlpatterns = [
    path("", views.index, name="index"),
    path("book/add/", views.add_book, name="add-book"),
    path("book/view/<str:book_id>/", views.view_book, name="view-book"),
    path("book/update/<str:book_id>/", views.update_book, name="update-book"),
    path("book/edit-category/", views.edit_category, name="edit-category"),
    path("book/edit-author/", views.edit_author, name="edit-author"),
    path("book/archive/<str:book_id>/", views.archive_book, name="archive-book"),
]

claire/models.py
from django.db import models


# Create your models here.
class EventDetails(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True)
    date = models.DateTimeField()
    medium = models.CharField(max_length=200)


class ParticipantDetails(models.Model):
    name = models.CharField(max_length=200)
    contact = models.CharField(max_length=200)


class AudienceDetails(models.Model):
    name = models.CharField(max_length=200)
    contact = models.CharField(max_length=200)


class RegistrationForm(models.Model):
    registration_date = models.DateTimeField(auto_now=True)
    event = models.OneToOneField(EventDetails, on_delete=models.CASCADE)
    audience = models.OneToOneField(AudienceDetails, on_delete=models.CASCADE)
    participant = models.OneToOneField(ParticipantDetails, on_delete=models.CASCADE)

lms/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return str(self.name)


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ManyToManyField(Author)
    description = models.TextField(null=True, blank=True)
    pages = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    is_archived = models.BooleanField(default=False)

    class Meta:
        ordering = ["-updated"]

    def __str__(self) -> str:
        return str(self.title)


class Category(models.Model):
    type = models.CharField(max_length=30)
    books = models.ManyToManyField(Book)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-updated"]

    def __str__(self) -> str:
        return str(self.type)

lms/forms.py
from django import forms

from .models import Book


class UpdateBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"

claire/views.py
from django.shortcuts import render

# Create your views here.

lms/views.py
from django.shortcuts import redirect, render
from django.urls import reverse

from .models import Author, Book, Category

last_query = ""


def filter_categories(request):
    global last_query
    query = request.GET.get("q", last_query)
    last_query = query
    categories = Category.objects.filter(type__icontains=query)

    filtered_categories = [category for category in categories]
    for category in Category.objects.all():
        if (
            category.books.filter(title__icontains=query)
            and category not in filtered_categories
        ):
            filtered_categories.append(category)

        for book in category.books.all():
            if (
                book.author.filter(name__icontains=query)
                and category not in filtered_categories
            ):
                filtered_categories.append(category)

    return filtered_categories


# Create your views here.
def index(request):
    global last_query
    filtered_categories = filter_categories(request)
    context = {
        "categories": filtered_categories,
        "query": last_query,
        "is_home": True,
    }
    return render(request, "lms/index.html", context)


def view_book(request, book_id):
    filtered_categories = filter_categories(request)
    book = Book.objects.get(pk=book_id)
    context = {
        "categories": filtered_categories,
        "book": book,
        "is_viewing": True,
    }
    return render(request, "lms/index.html", context)


def add_book(request):
    filtered_categories = filter_categories(request)
    authors = Author.objects.all()

    if request.method == "POST":
        authors = request.POST.getlist("book_author")
        categories = request.POST.getlist("book_categories")
        book = Book(
            title=request.POST["book_title"],
            description=request.POST["book_description"],
            pages=request.POST["book_pages"],
        )
        book.save()
        book.author.set(Author.objects.filter(name__in=authors))
        book.category_set.set(Category.objects.filter(type__in=categories))
        return redirect(reverse("lms:index"))

    context = {
        "categories": filtered_categories,
        "is_adding": True,
        "authors": authors,
    }
    return render(request, "lms/index.html", context)


def update_book(request, book_id):
    filtered_categories = filter_categories(request)
    book = Book.objects.get(pk=book_id)

    if request.method == "POST":
        new_authors = request.POST.getlist("book_author")
        new_categories = request.POST.getlist("book_categories")

        book.title = request.POST["book_title"]
        book.description = request.POST["book_description"]
        book.pages = request.POST["book_pages"]

        book.author.set(Author.objects.filter(name__in=new_authors))
        book.category_set.set(Category.objects.filter(type__in=new_categories))
        book.save()
        return redirect(reverse("lms:index"))

    authors = Author.objects.all()
    context = {
        "categories": filtered_categories,
        "book": book,
        "authors": authors,
        "is_updating": True,
    }
    return render(request, "lms/index.html", context)


def edit_category(request):
    filtered_categories = filter_categories(request)
    all_books = Book.objects.all()

    if request.method == "POST":
        type = request.POST["option"]
        books = request.POST.getlist("books")
        category, _ = Category.objects.get_or_create(type=type)
        category.books.set(Book.objects.filter(title__in=books))
        category.save()
        return redirect(reverse("lms:index"))

    context = {
        "label": "Category",
        "categories": filtered_categories,
        "books": all_books,
        "is_editing": True,
    }
    return render(request, "lms/index.html", context)


def edit_author(request):
    filtered_categories = filter_categories(request)
    authors = Author.objects.all()
    all_books = Book.objects.all()

    if request.method == "POST":
        name = request.POST["option"]
        books = request.POST.getlist("books")
        author, _ = Author.objects.get_or_create(name=name)
        author.book_set.set(Book.objects.filter(title__in=books))
        author.save()
        return redirect(reverse("lms:index"))

    context = {
        "label": "Author",
        "categories": filtered_categories,
        "authors": authors,
        "books": all_books,
        "is_editing": True,
    }
    return render(request, "lms/index.html", context)


def archive_book(request, book_id):
    book = Book.objects.get(pk=book_id)
    book.is_archived = True
    book.save()
    return redirect(reverse("lms:index"))

lms/templates/lms/edit_form.html
<form id="edit-form" class="modal" action="" method="post">
  {% csrf_token %}
  <div class="modal-preview">
    <div class="modal-preview-inner">
      <div class="form-group">
        <label for="option">{{ label }}</label>
        <input required id="option" name="option" list="option-list" placeholder="Enter {{ label|lower }}...">
        <datalist id="option-list">
          <select id="option">
            {% if authors %}
            {% for author in authors %}
            <option value="{{ author }}">{{ author }}</option>
            {% endfor %}
            {% else %}
            {% for category in categories %}
            <option value="{{ category }}">{{ category }}</option>
            {% endfor %}
            {% endif %}
          </select>
        </datalist>
      </div>

      <div class="form-group">
        <label for="books">Books</label>
        <select name="books" multiple>
          {% for book in books %}
          {% if not book.is_archived %}
          <option id="book-option" value="{{ book }}" data-author="{{ book.author.all }}"
            data-category="{{ book.category_set.all }}">
            {{ book }}
          </option>
          {% endif %}
          {% endfor %}
        </select>
      </div>
    </div>
  </div>
</form>
<div class="buttons">
  <input type="submit" class="button" form="edit-form" value="Save">
  <a href="{% url 'lms:index' %}" class="button">Cancel</a>
</div>

lms/templates/lms/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="shortcut icon" href="{% static 'images/lms.png' %}" type="image/png" />
  <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
  <title>Library Management System</title>
</head>

<body class="{% if not is_home %}no-scroll{% endif %}">
  <main>
    <!-- Heading -->
    <h1 class="heading">Library Management System</h1>

    <!-- Searchbar -->
    <form class="searchbar" action="{% url 'lms:index' %}" method="get">
      <input type="text" name="q" value="{{ query }}" placeholder="Search for books, authors, and categories..." />
    </form>

    <!-- Categories w/ Books -->
    {% for category in categories %}
    <div class="category" data-type="{{ category.type|upper }}">
      <div class="books-wrapper">
        {% for book in category.books.all %}
        {% if not book.is_archived %}
        <a href="{% url 'lms:view-book' book.id %}" class="book">
          <p>{{ book|truncatechars:14 }}</p>
        </a>
        {% endif %}
        {% endfor %}
      </div>
    </div>
    {% endfor %}

    <!-- Popups -->
    {% if is_viewing %}
    {% include "lms/view_book.html" %}
    {% elif is_editing %}
    {% include "lms/edit_form.html" %}
    {% elif is_updating %}
    {% include "lms/update_form.html" %}
    {% elif is_adding %}
    {% include "lms/update_form.html" %}
    {% else %}
    <!-- Buttons -->
    <div class="buttons">
      <a href="{% url 'lms:add-book' %}" class="button">Add Book</a>
      <a href="{% url 'lms:edit-category' %}" class="button">Edit Category</a>
      <a href="{% url 'lms:edit-author' %}" class="button">Edit Author</a>
    </div>
    {% endif %}
  </main>
  <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

lms/templates/lms/update_form.html
<form id="form" class="modal" action="" method="post">
  {% csrf_token %}
  <div class="modal-preview">
    <div class="modal-preview-inner">
      <input class="book-title" name="book_title" value="{{ book }}" placeholder="Enter book title...">
      <textarea class="book-description" name="book_description" rows="10"
        placeholder="Enter book description...">{{ book.description }}</textarea>
      <div class="options">
        <div class="book-author">
          <select name="book_author" multiple>
            {% for author in authors %}
            {% if author in book.author.all %}
            <option value="{{ author }}" selected>{{ author }}</option>
            {% else %}
            <option value="{{ author }}">{{ author }}</option>
            {% endif %}
            {% endfor %}
          </select>
        </div>
        <div class="book-categories">
          <select name="book_categories" multiple>
            {% for category in categories %}
            {% if category in book.category_set.all %}
            <option value="{{ category }}" selected>{{ category }}</option>
            {% else %}
            <option value="{{ category }}">{{ category }}</option>
            {% endif %}
            {% endfor %}
          </select>
        </div>
      </div>
      <input class="book-pages" type="number" name="book_pages" value="{{ book.pages }}" placeholder="Enter pages...">
    </div>
  </div>
</form>
<div class="buttons">
  <input type="submit" class="button" form="form" value="Save">
  <a href="{{ request.META.HTTP_REFERER }}" class="button">Cancel</a>
</div>

lms/templates/lms/view_book.html
<div class="modal">
  <div class="modal-preview">
    <div class="modal-preview-inner">
      <h2 class="book-title">{{ book }}</h2>
      <p class="book-description">{{ book.description }}</p>
      <p class="book-author">
        {{ book.author.all|join:", " }}
      </p>
      <p class="book-categories">
        {{ book.category_set.all|join:", " }}
      </p>
      <span class="book-pages">{{ book.pages }}</span>
    </div>
  </div>
</div>
<div class="buttons">
  <a href="{% url 'lms:update-book' book.id %}" class="button">Update</a>
  <a href="{% url 'lms:archive-book' book.id %}" class="button">Archive</a>
  <a href="{% url 'lms:index' %}" class="button">Back</a>
</div>